### ISSUE TITLE
ctrl-s in options script

### ISSUE THREAD

**Issue by louisVottero** [louisVottero/vtool#110]
```
# Traceback (most recent call last):
#   File "E:/dev/git/vtool/python\vtool\qt_ui.py", line 4566, in _save
#     new_last_modified = util_file.get_last_modified_date(self.filepath)
#   File "E:/dev/git/vtool/python\vtool\util_file.py", line 1816, in get_last_modified_date
#     mtime = os.path.getmtime(filepath)
#   File "E:/Program Files/Autodesk/Maya2022\Python37\lib\genericpath.py", line 55, in getmtime
#     return os.stat(filename).st_mtime
# TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by louisVottero** [comment]
fixed here
https://github.com/louisVottero/vtool/pull/124
