### ISSUE TITLE
removing a tag from shape combo produces this error

### ISSUE THREAD

**Issue by louisVottero** [louisVottero/vtool#111]
```
# Traceback (most recent call last):
#   File "E:/dev/git/vtool/python\vtool\maya_lib\ui_lib\ui_shape_combo.py", line 1574, in _right_click_remove_tag
#     self.remove_tag(self._right_click_tag)
#   File "E:/dev/git/vtool/python\vtool\maya_lib\ui_lib\ui_shape_combo.py", line 1625, in remove_tag
#     self.manager.remove_tag(tag_name)
#   File "E:/dev/git/vtool/python\vtool\maya_lib\blendshape.py", line 2142, in remove_tag
#     data_dict.pop(tag_name)
# KeyError: 'test'
```

**Comment by louisVottero** [comment]
Fixed here:
https://github.com/louisVottero/vtool/pull/123
