### ISSUE TITLE
switching projects error

### ISSUE THREAD

**Issue by louisVottero** [louisVottero/vtool#319]
```
V:		Auto focus
// V:		Imported control_cvs data.
V: Error!	Traceback (most recent call last):	
V:		  File "/users/lrpvottero/git/vtool/python/vtool/util_file.py", line 2429, in create_dir	
V:		    os.makedirs(full_path)	
V:		  File "/usr/autodesk/maya2023/lib/python3.9/os.py", line 210, in makedirs	
V:		    head, tail = path.split(name)	
V:		  File "/usr/autodesk/maya2023/lib/python3.9/posixpath.py", line 103, in split	
V:		    p = os.fspath(p)	
V:		TypeError: expected str, bytes or os.PathLike object, not bool
# Traceback (most recent call last):
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_process_manager.py", line 1811, in set_project_directory
#     self.clear_stage()
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_process_manager.py", line 1884, in clear_stage
#     self._clear_data()
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_process_manager.py", line 1167, in _clear_data
#     self.data_widget.clear_data()
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_data.py", line 307, in clear_data
#     self.set_directory('')
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_data.py", line 301, in set_directory
#     self.data_widget.set_directory(directory)
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_data.py", line 449, in set_directory
#     self._set_file_widget_directory(directory)
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_data.py", line 362, in _set_file_widget_directory
#     self.file_widget.set_temp_sub_folder(sub_folder)
#   File "/users/lrpvottero/git/vtool/python/vtool/qt_ui.py", line 1751, in set_temp_sub_folder
#     self.data_class.set_temp_sub_folder(folder_name)
# AttributeError: 'NoneType' object has no attribute 'set_temp_sub_folder'
V: Error!	Traceback (most recent call last):	
V:		  File "/users/lrpvottero/git/vtool/python/vtool/util_file.py", line 2429, in create_dir	
V:		    os.makedirs(full_path)	
V:		  File "/usr/autodesk/maya2023/lib/python3.9/os.py", line 210, in makedirs	
V:		    head, tail = path.split(name)	
V:		  File "/usr/autodesk/maya2023/lib/python3.9/posixpath.py", line 103, in split	
V:		    p = os.fspath(p)	
V:		TypeError: expected str, bytes or os.PathLike object, not bool
# Traceback (most recent call last):
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_process_manager.py", line 1811, in set_project_directory
#     self.clear_stage()
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_process_manager.py", line 1884, in clear_stage
#     self._clear_data()
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_process_manager.py", line 1167, in _clear_data
#     self.data_widget.clear_data()
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_data.py", line 307, in clear_data
#     self.set_directory('')
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_data.py", line 301, in set_directory
#     self.data_widget.set_directory(directory)
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_data.py", line 449, in set_directory
#     self._set_file_widget_directory(directory)
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_data.py", line 362, in _set_file_widget_directory
#     self.file_widget.set_temp_sub_folder(sub_folder)
#   File "/users/lrpvottero/git/vtool/python/vtool/qt_ui.py", line 1751, in set_temp_sub_folder
#     self.data_class.set_temp_sub_folder(folder_name)
# AttributeError: 'NoneType' object has no attribute 'set_temp_sub_folder'
V: Error!	Traceback (most recent call last):	
V:		  File "/users/lrpvottero/git/vtool/python/vtool/util_file.py", line 2429, in create_dir	
V:		    os.makedirs(full_path)	
V:		  File "/usr/autodesk/maya2023/lib/python3.9/os.py", line 210, in makedirs	
V:		    head, tail = path.split(name)	
V:		  File "/usr/autodesk/maya2023/lib/python3.9/posixpath.py", line 103, in split	
V:		    p = os.fspath(p)	
V:		TypeError: expected str, bytes or os.PathLike object, not bool
# Traceback (most recent call last):
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_process_manager.py", line 1811, in set_project_directory
#     self.clear_stage()
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_process_manager.py", line 1884, in clear_stage
#     self._clear_data()
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_process_manager.py", line 1167, in _clear_data
#     self.data_widget.clear_data()
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_data.py", line 307, in clear_data
#     self.set_directory('')
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_data.py", line 301, in set_directory
#     self.data_widget.set_directory(directory)
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_data.py", line 449, in set_directory
#     self._set_file_widget_directory(directory)
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_data.py", line 362, in _set_file_widget_directory
#     self.file_widget.set_temp_sub_folder(sub_folder)
#   File "/users/lrpvottero/git/vtool/python/vtool/qt_ui.py", line 1751, in set_temp_sub_folder
#     self.data_class.set_temp_sub_folder(folder_name)
# AttributeError: 'NoneType' object has no attribute 'set_temp_sub_folder'
V: Error!	Traceback (most recent call last):	
V:		  File "/users/lrpvottero/git/vtool/python/vtool/util_file.py", line 2429, in create_dir	
V:		    os.makedirs(full_path)	
V:		  File "/usr/autodesk/maya2023/lib/python3.9/os.py", line 210, in makedirs	
V:		    head, tail = path.split(name)	
V:		  File "/usr/autodesk/maya2023/lib/python3.9/posixpath.py", line 103, in split	
V:		    p = os.fspath(p)	
V:		TypeError: expected str, bytes or os.PathLike object, not bool
# Traceback (most recent call last):
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_process_manager.py", line 1811, in set_project_directory
#     self.clear_stage()
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_process_manager.py", line 1884, in clear_stage
#     self._clear_data()
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_process_manager.py", line 1167, in _clear_data
#     self.data_widget.clear_data()
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_data.py", line 307, in clear_data
#     self.set_directory('')
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_data.py", line 301, in set_directory
#     self.data_widget.set_directory(directory)
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_data.py", line 449, in set_directory
#     self._set_file_widget_directory(directory)
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_data.py", line 362, in _set_file_widget_directory
#     self.file_widget.set_temp_sub_folder(sub_folder)
#   File "/users/lrpvottero/git/vtool/python/vtool/qt_ui.py", line 1751, in set_temp_sub_folder
#     self.data_class.set_temp_sub_folder(folder_name)
# AttributeError: 'NoneType' object has no attribute 'set_temp_sub_folder'
```

**Comment by louisVottero** [comment]
```
V: Error!	Traceback (most recent call last):	
V:		  File "E:/dev/git/vtool/python\vtool\util_file.py", line 2456, in create_dir	
V:		    os.makedirs(full_path)	
V:		  File "C:/Program Files/Autodesk/Maya2022\Python37\lib\os.py", line 208, in makedirs	
V:		    head, tail = path.split(name)	
V:		  File "C:/Program Files/Autodesk/Maya2022\Python37\lib\ntpath.py", line 183, in split	
V:		    p = os.fspath(p)	
V:		TypeError: expected str, bytes or os.PathLike object, not bool
# Traceback (most recent call last):
#   File "E:/dev/git/vtool/python\vtool\process_manager\ui_process_manager.py", line 728, in _item_selection_changed
#     self._update_process(name)
#   File "E:/dev/git/vtool/python\vtool\process_manager\ui_process_manager.py", line 803, in _update_process
#     self._clear_data()
#   File "E:/dev/git/vtool/python\vtool\process_manager\ui_process_manager.py", line 1167, in _clear_data
#     self.data_widget.clear_data()
#   File "E:/dev/git/vtool/python\vtool\process_manager\ui_data.py", line 307, in clear_data
#     self.set_directory('')
#   File "E:/dev/git/vtool/python\vtool\process_manager\ui_data.py", line 301, in set_directory
#     self.data_widget.set_directory(directory)
#   File "E:/dev/git/vtool/python\vtool\process_manager\ui_data.py", line 449, in set_directory
#     self._set_file_widget_directory(directory)
#   File "E:/dev/git/vtool/python\vtool\process_manager\ui_data.py", line 362, in _set_file_widget_directory
#     self.file_widget.set_temp_sub_folder(sub_folder)
#   File "E:/dev/git/vtool/python\vtool\qt_ui.py", line 1751, in set_temp_sub_folder
#     self.data_class.set_temp_sub_folder(folder_name)
# AttributeError: 'NoneType' object has no attribute 'set_temp_sub_folder'
```

**Comment by louisVottero** [comment]
These should be fixed with this pull request
https://github.com/louisVottero/vtool/pull/327
