### ISSUE TITLE
No template widget 

### ISSUE THREAD

**Issue by louisVottero** [louisVottero/vtool#362]
```
# Traceback (most recent call last):
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_process_manager.py", line 735, in _item_selection_changed
#     self._update_process(name)
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_process_manager.py", line 768, in _update_process
#     self.template_holder_splitter.main_layout.addWidget(template.widget())
# AttributeError: 'NoneType' object has no attribute 'widget'
```

**Comment by louisVottero** [comment]
fixed this branch
https://github.com/louisVottero/vtool/pull/374
