### ISSUE TITLE
Ramen line = None

### ISSUE THREAD

**Issue by louisVottero** [louisVottero/vtool#370]
```
# Traceback (most recent call last):
#   File "/jobs/site/tools/vtool/python/vtool/ramen/ui_lib/ui_ramen.py", line 160, in _run_graph
#     eval.run_ui(widget.main_view.base)
#   File "/jobs/site/tools/vtool/python/vtool/ramen/eval.py", line 32, in run_ui
#     run(items)
#   File "/jobs/site/tools/vtool/python/vtool/ramen/eval.py", line 79, in run
#     node.run()
#   File "/jobs/site/tools/vtool/python/vtool/ramen/ui_lib/ui_nodes.py", line 3032, in run
#     self.run_inputs()
#   File "/jobs/site/tools/vtool/python/vtool/ramen/ui_lib/ui_nodes.py", line 3554, in run_inputs
#     super(RigItem, self).run_inputs()
#   File "/jobs/site/tools/vtool/python/vtool/ramen/ui_lib/ui_nodes.py", line 2983, in run_inputs
#     self.run_connection(socket_name)
#   File "/jobs/site/tools/vtool/python/vtool/ramen/ui_lib/ui_nodes.py", line 3012, in run_connection
#     input_node.run()
#   File "/jobs/site/tools/vtool/python/vtool/ramen/ui_lib/ui_nodes.py", line 3038, in run
#     self._implement_run(socket)
#   File "/jobs/site/tools/vtool/python/vtool/ramen/ui_lib/ui_nodes.py", line 3536, in _implement_run
#     self._unparent()
#   File "/jobs/site/tools/vtool/python/vtool/ramen/ui_lib/ui_nodes.py", line 3477, in _unparent
#     nodes = self.get_output_connected_nodes()
#   File "/jobs/site/tools/vtool/python/vtool/ramen/ui_lib/ui_nodes.py", line 2971, in get_output_connected_nodes
#     found.append(line.target.get_parent())
# AttributeError: 'NoneType' object has no attribute 'get_parent'
```

**Comment by louisVottero** [comment]
This is fixed in this pull request
https://github.com/louisVottero/vtool/pull/379
