### ISSUE TITLE
Missing Joint shouldn't mess up skin weight import

### ISSUE THREAD

**Issue by louisVottero** [louisVottero/vtool#371]
```
V: Error!	Traceback (most recent call last):	
V:		  File "/jobs/site/tools/vtool/python/vtool/util.py", line 78, in wrapper	
V:		    return_value = function(*args, **kwargs)	
V:		  File "/jobs/site/tools/vtool/python/vtool/data.py", line 1612, in import_data	
V:		    self._import_maya_data(filepath, selection)	
V:		  File "/jobs/site/tools/vtool/python/vtool/data.py", line 1282, in _import_maya_data	
V:		    result = self.import_skin_weights(folder_path, mesh, first=first)	
V:		  File "/jobs/site/tools/vtool/python/vtool/data.py", line 1483, in import_skin_weights	
V:		    skin_inst.add_influence(influence)	
V:		  File "/jobs/site/tools/vtool/python/vtool/maya_lib/deform.py", line 96, in add_influence	
V:		    cmds.addAttr(transform_name, ln='lockInfluenceWeights', sn='liw', at='bool', dv=0)	
V:		ValueError: No object matches name: root|chassis
```

**Comment by louisVottero** [comment]
fixed in this pull request
https://github.com/louisVottero/vtool/issues/371
