### ISSUE TITLE
Create Joints on Curve in the UI

### ISSUE THREAD

**Issue by louisVottero** [louisVottero/vtool#376]
```
# Traceback (most recent call last):
#   File "E:/dev/git/vtool/python\vtool\maya_lib\ui_lib\ui_rig.py", line 905, in _joints_on_curve
#     geo.create_oriented_joints_on_curve(selection[0], count)
#   File "E:/dev/git/vtool/python\vtool\maya_lib\core.py", line 456, in wrapper
#     raise RuntimeError
# RuntimeError
select -add curve1 ;
V: Error!	Traceback (most recent call last):	
V:		  File "E:/dev/git/vtool/python\vtool\maya_lib\core.py", line 439, in wrapper	
V:		    return_value = function(*args, **kwargs)	
V:		  File "E:/dev/git/vtool/python\vtool\maya_lib\geo.py", line 2779, in create_oriented_joints_on_curve	
V:		    length = cmds.arclen(curve, ch=False)	
V:		RuntimeError: Command arclen failed. Open Script Editor for details.	
V:		
# Traceback (most recent call last):
#   File "E:/dev/git/vtool/python\vtool\maya_lib\core.py", line 439, in wrapper
#     return_value = function(*args, **kwargs)
#   File "E:/dev/git/vtool/python\vtool\maya_lib\geo.py", line 2779, in create_oriented_joints_on_curve
#     length = cmds.arclen(curve, ch=False)
# RuntimeError: Command arclen failed. Open Script Editor for details.
# 
# # 
# During handling of the above exception, another exception occurred:

# Traceback (most recent call last):
#   File "E:/dev/git/vtool/python\vtool\maya_lib\ui_lib\ui_rig.py", line 905, in _joints_on_curve
#     geo.create_oriented_joints_on_curve(selection[0], count)
#   File "E:/dev/git/vtool/python\vtool\maya_lib\core.py", line 456, in wrapper
#     raise RuntimeError
# RuntimeError
```

**Comment by louisVottero** [comment]
This is fixed in this pull 
https://github.com/louisVottero/vtool/pull/383
