### ISSUE TITLE
code completion bug swapcase not working with unicode

### ISSUE THREAD

**Issue by louisVottero** [louisVottero/vtool#431]
```
# Traceback (most recent call last):
#   File "E:/dev/git/vtool/python\vtool\qt_ui.py", line 4496, in keyPressEvent
#     result = self.completer.handle_text(text)
#   File "E:/dev/git/vtool/python\vtool\qt_ui.py", line 5631, in handle_text
#     passed = self.handle_import_load(text, cursor)
#   File "E:/dev/git/vtool/python\vtool\qt_ui.py", line 5869, in handle_import_load
#     custom_defined.sort(key=str.swapcase)
# TypeError: descriptor 'swapcase' requires a 'str' object but received a 'unicode'
# Traceback (most recent call last):
#   File "E:/dev/git/vtool/python\vtool\qt_ui.py", line 4496, in keyPressEvent
#     result = self.completer.handle_text(text)
#   File "E:/dev/git/vtool/python\vtool\qt_ui.py", line 5631, in handle_text
#     passed = self.handle_import_load(text, cursor)
#   File "E:/dev/git/vtool/python\vtool\qt_ui.py", line 5869, in handle_import_load
#     custom_defined.sort(key=str.swapcase)
# TypeError: descriptor 'swapcase' requires a 'str' object but received a 'unicode'
# Traceback (most recent call last):
#   File "E:/dev/git/vtool/python\vtool\qt_ui.py", line 4496, in keyPressEvent
#     result = self.completer.handle_text(text)
#   File "E:/dev/git/vtool/python\vtool\qt_ui.py", line 5631, in handle_text
#     passed = self.handle_import_load(text, cursor)
#   File "E:/dev/git/vtool/python\vtool\qt_ui.py", line 5869, in handle_import_load
#     custom_defined.sort(key=str.swapcase)
# TypeError: descriptor 'swapcase' requires a 'str' object but received a 'unicode'
```

**Comment by louisVottero** [comment]
Fixed here 
https://github.com/louisVottero/vtool/pull/453
