### ISSUE TITLE
Data list right click menu might not work if no other item selected - easy fix

### ISSUE THREAD

**Issue by louisVottero** [louisVottero/vtool#445]
```
# Traceback (most recent call last):
#   File "E:/dev/git/vtool/python\vtool\process_manager\ui_data.py", line 651, in _create_data
#     if current_item.text(1) == 'Folder':
# AttributeError: 'NoneType' object has no attribute 'text'
# Traceback (most recent call last):
#   File "E:/dev/git/vtool/python\vtool\process_manager\ui_data.py", line 651, in _create_data
#     if current_item.text(1) == 'Folder':
# AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by louisVottero** [comment]
Fixed here:
https://github.com/louisVottero/vtool/pull/452
