### ISSUE TITLE
fix needed - Auto camera position 

### ISSUE THREAD

**Issue by louisVottero** [louisVottero/vtool#447]
Sometimes the camera can be named persp1,  fix_camera should at least check if persp camera exists first .

```
# Traceback (most recent call last):
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_data.py", line 2878, in _open_file
#     self.data_class.open()
#   File "/users/lrpvottero/git/vtool/python/vtool/data.py", line 3340, in open
#     self._after_open()
#   File "/users/lrpvottero/git/vtool/python/vtool/data.py", line 3220, in _after_open
#     self._center_view()
#   File "/users/lrpvottero/git/vtool/python/vtool/data.py", line 627, in _center_view
#     maya_lib.core.auto_focus_view()
#   File "/users/lrpvottero/git/vtool/python/vtool/maya_lib/core.py", line 2035, in auto_focus_view
#     fix_camera()
#   File "/users/lrpvottero/git/vtool/python/vtool/maya_lib/core.py", line 2039, in fix_camera
#     camera_pos = cmds.xform('persp', q=True, ws=True, t=True)
# ValueError: No object matches name: persp
```

**Comment by louisVottero** [comment]
This is fixed with this pull
https://github.com/louisVottero/vtool/pull/451
