### ISSUE TITLE
Switching projects caused this error in curve.py

### ISSUE THREAD

**Issue by louisVottero** [louisVottero/vtool#467]
```
# Traceback (most recent call last):
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_process_manager.py", line 1819, in set_project_directory
#     self.clear_stage()
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_process_manager.py", line 1891, in clear_stage
#     self._clear_data()
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_process_manager.py", line 1175, in _clear_data
#     self.data_widget.clear_data()
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_data.py", line 307, in clear_data
#     self.set_directory('')
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_data.py", line 301, in set_directory
#     self.data_widget.set_directory(directory)
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_data.py", line 443, in set_directory
#     self._set_file_widget_directory(directory)
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_data.py", line 364, in _set_file_widget_directory
#     self.file_widget.set_directory(folder)
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_data.py", line 1598, in set_directory
#     super(DataFileWidget, self).set_directory(directory)
#   File "/users/lrpvottero/git/vtool/python/vtool/qt_ui.py", line 1806, in set_directory
#     self.option_widget.set_directory(history_directory)
#   File "/users/lrpvottero/git/vtool/python/vtool/qt_ui.py", line 2079, in set_directory
#     self.tab_update()
#   File "/users/lrpvottero/git/vtool/python/vtool/process_manager/ui_data.py", line 2118, in tab_update
#     curves = self.data_class.get_curves()
#   File "/users/lrpvottero/git/vtool/python/vtool/data.py", line 719, in get_curves
#     library = self._initialize_library(filename)
#   File "/users/lrpvottero/git/vtool/python/vtool/data.py", line 654, in _initialize_library
#     library.set_directory(directory)
#   File "/users/lrpvottero/git/vtool/python/vtool/maya_lib/curve.py", line 337, in set_directory
#     self._load_libraries()
#   File "/users/lrpvottero/git/vtool/python/vtool/maya_lib/curve.py", line 216, in _load_libraries
#     files = os.listdir(self.curve_data_path)
```

**Comment by louisVottero** [comment]
added error in this case, should be working slightly better
https://github.com/louisVottero/vtool/pull/484
