### ISSUE TITLE
Vetala Code Completion error: trying to auto complete on string in quotes. 

### ISSUE THREAD

**Issue by louisVottero** [louisVottero/vtool#490]
```
FIXME Subscripted generics cannot be used with class and instance checks
# Traceback (most recent call last):
#   File "/users/lrpvottero/git/vtool/python/vtool/qt_ui.py", line 4496, in keyPressEvent
#     result = self.completer.handle_text(text)
#   File "/users/lrpvottero/git/vtool/python/vtool/qt_ui.py", line 5631, in handle_text
#     passed = self.handle_import_load(text, cursor)
#   File "/users/lrpvottero/git/vtool/python/vtool/qt_ui.py", line 5867, in handle_import_load
#     self.string_model.setStringList(custom_defined)
# TypeError: # 'PySide2.QtCore.QStringListModel.setStringList' called with wrong argument types:
#   PySide2.QtCore.QStringListModel.setStringList(NoneType)
# Supported signatures:
  PySide2.QtCore.QStringListModel.setStringList(typing.Sequence[str])
```

**Comment by louisVottero** [comment]
Fixed with this pull 
https://github.com/louisVottero/vtool/pull/496
