### ISSUE TITLE
versions error

### ISSUE THREAD

**Issue by louisVottero** [louisVottero/vtool#500]
```
# Traceback (most recent call last):
#   File "/users/lrpvottero/git/vtool/python/vtool/qt_ui.py", line 1659, in _tab_changed
#     self._show_history()
#   File "/users/lrpvottero/git/vtool/python/vtool/qt_ui.py", line 1616, in _show_history
#     self.update_history()
#   File "/users/lrpvottero/git/vtool/python/vtool/qt_ui.py", line 1760, in update_history
#     self.history_widget.set_directory(history_directory)
#   File "/users/lrpvottero/git/vtool/python/vtool/qt_ui.py", line 2038, in set_directory
#     self.version_list.set_directory(directory, refresh=True)
#   File "/users/lrpvottero/git/vtool/python/vtool/qt_ui.py", line 1161, in set_directory
#     self.refresh()
#   File "/users/lrpvottero/git/vtool/python/vtool/qt_ui.py", line 1138, in refresh
#     files = self._get_files()
#   File "/users/lrpvottero/git/vtool/python/vtool/qt_ui.py", line 1924, in _get_files
#     version_data = version_tool.get_organized_version_data()
#   File "/users/lrpvottero/git/vtool/python/vtool/util_file.py", line 409, in get_organized_version_data
#     versions = self.get_versions(return_version_numbers_also=True)
#   File "/users/lrpvottero/git/vtool/python/vtool/util_file.py", line 602, in get_versions
#     pass_dict[pass_files[0][inc]] = pass_files[1][inc]
# IndexError: list index out of range
```

**Comment by louisVottero** [comment]
```
# Traceback (most recent call last):
#   File "E:/dev/git/vtool/python\vtool\qt_ui.py", line 1659, in _tab_changed
#     self._show_history()
#   File "E:/dev/git/vtool/python\vtool\qt_ui.py", line 1616, in _show_history
#     self.update_history()
#   File "E:/dev/git/vtool/python\vtool\qt_ui.py", line 1760, in update_history
#     self.history_widget.set_directory(history_directory)
#   File "E:/dev/git/vtool/python\vtool\qt_ui.py", line 2038, in set_directory
#     self.version_list.set_directory(directory, refresh=True)
#   File "E:/dev/git/vtool/python\vtool\qt_ui.py", line 1161, in set_directory
#     self.refresh()
#   File "E:/dev/git/vtool/python\vtool\qt_ui.py", line 1138, in refresh
#     files = self._get_files()
#   File "E:/dev/git/vtool/python\vtool\qt_ui.py", line 1924, in _get_files
#     version_data = version_tool.get_organized_version_data()
#   File "E:/dev/git/vtool/python\vtool\util_file.py", line 456, in get_organized_version_data
#     if int(line_info_dict['version']) not in version_numbers:
# TypeError: 'in <string>' requires string as left operand, not int
```

**Comment by louisVottero** [comment]
Fixed here 
https://github.com/louisVottero/vtool/commit/5b31c69882191982390ab79f1a946d1eefb4880e
