### ISSUE TITLE
Error, process copy paste

### ISSUE THREAD

**Issue by louisVottero** [louisVottero/vtool#518]
```
# Traceback (most recent call last):
#   File "E:/dev/git/vtool/python\vtool\process_manager\ui_view.py", line 1475, in paste_process
#     new_process = process.copy_process(source_process, target_process.get_path())
#   File "E:/dev/git/vtool/python\vtool\process_manager\process.py", line 3508, in copy_process
#     copy_process_data(source_process, new_process, data_folder)
#   File "E:/dev/git/vtool/python\vtool\process_manager\process.py", line 3709, in copy_process_data
#     copy(filepath, destination_directory, data_name)
#   File "E:/dev/git/vtool/python\vtool\process_manager\process.py", line 3426, in copy
#     copied_path = util_file.copy_file(source_file_or_folder, target_file_or_folder)
#   File "E:/dev/git/vtool/python\vtool\util_file.py", line 2619, in copy_file
#     shutil.copyfile(filepath, filepath_destination)
#   File "C:\Program Files\Autodesk\Maya2022\Python27\lib\shutil.py", line 84, in copyfile
#     copyfileobj(fsrc, fdst)
#   File "C:\Program Files\Autodesk\Maya2022\Python27\lib\shutil.py", line 49, in copyfileobj
#     buf = fsrc.read(length)
# IOError: [Errno 2] No such file or directory
```

**Comment by louisVottero** [comment]
This is erroring on the build copy data
```
# Traceback (most recent call last):
#   File "E:/dev/git/vtool/python\vtool\process_manager\ui_view.py", line 2249, in _paste
#     self._paste_data()
#   File "E:/dev/git/vtool/python\vtool\process_manager\ui_view.py", line 2296, in _paste_data
#     process.copy_process_data(self.process, other_process_inst, name, sub_folder=folder_name)
#   File "E:/dev/git/vtool/python\vtool\process_manager\process.py", line 3709, in copy_process_data
#     copy(filepath, destination_directory, data_name)
#   File "E:/dev/git/vtool/python\vtool\process_manager\process.py", line 3426, in copy
#     copied_path = util_file.copy_file(source_file_or_folder, target_file_or_folder)
#   File "E:/dev/git/vtool/python\vtool\util_file.py", line 2619, in copy_file
#     shutil.copyfile(filepath, filepath_destination)
#   File "C:\Program Files\Autodesk\Maya2022\Python27\lib\shutil.py", line 84, in copyfile
#     copyfileobj(fsrc, fdst)
#   File "C:\Program Files\Autodesk\Maya2022\Python27\lib\shutil.py", line 49, in copyfileobj
#     buf = fsrc.read(length)
# IOError: [Errno 2] No such file or directory
```
