### ISSUE TITLE
correctives bug

### ISSUE THREAD

**Issue by louisVottero** [louisVottero/vtool#529]
```
V: Error!	Traceback (most recent call last):	
V:		  File "E:/dev/git/vtool/python\vtool\maya_lib\core.py", line 433, in wrapper	
V:		    return_value = function(*args, **kwargs)	
V:		  File "E:/dev/git/vtool/python\vtool\maya_lib\ui_lib\ui_corrective.py", line 1493, in add_mesh	
V:		    corrective.PoseManager().toggle_visibility(mesh, pose_name)	
V:		  File "E:/dev/git/vtool/python\vtool\maya_lib\corrective.py", line 563, in toggle_visibility	
V:		    pose.toggle_vis(index, view_only)	
V:		  File "E:/dev/git/vtool/python\vtool\maya_lib\corrective.py", line 2210, in toggle_vis	
V:		    self.visibility_off(mesh, view_only)	
V:		  File "E:/dev/git/vtool/python\vtool\maya_lib\corrective.py", line 2150, in visibility_off	
V:		    if geo.is_mesh_position_same(target_mesh, mesh, 0.0001):	
V:		  File "E:/dev/git/vtool/python\vtool\maya_lib\geo.py", line 480, in is_mesh_position_same	
V:		    different = get_position_different(mesh1, mesh2, tolerance)	
V:		  File "E:/dev/git/vtool/python\vtool\maya_lib\geo.py", line 586, in get_position_different	
V:		    if not util_math.is_the_same_number(point1[inc][sub_inc], point2[inc][sub_inc], tolerance):	
V:		TypeError: 'float' object has no attribute '__getitem__'
V: Error!	Traceback (most recent call last):	
V:		  File "E:/dev/git/vtool/python\vtool\maya_lib\ui_lib\ui_corrective.py", line 1572, in _button_sculpt	
V:		    self.mesh_widget.add_mesh()	
V:		  File "E:/dev/git/vtool/python\vtool\maya_lib\core.py", line 450, in wrapper	
V:		    raise RuntimeError	
V:		RuntimeError
```

**Comment by louisVottero** [comment]
should be fixed here
https://github.com/louisVottero/vtool/pull/530
