### ISSUE TITLE
Duplicate Process - code manifest does not sync on/off state properly

### ISSUE THREAD

**Issue by louisVottero** [louisVottero/vtool#538]

**Comment by louisVottero** [comment]
# Traceback (most recent call last):
#   File "E:/dev/git/vtool/python\vtool\process_manager\ui_view.py", line 916, in _duplicate_process
#     new_process = process.copy_process(source_process, target_directory)
#   File "E:/dev/git/vtool/python\vtool\process_manager\process.py", line 3538, in copy_process
#     copy_process(source_sub_process, new_process.get_path())
#   File "E:/dev/git/vtool/python\vtool\process_manager\process.py", line 3523, in copy_process
#     copy_process_code(source_process, new_process, code_folder)
#   File "E:/dev/git/vtool/python\vtool\process_manager\process.py", line 3759, in copy_process_code
#     code_folder_path = target_process.create_code(code_name, 'script.python')
#   File "E:/dev/git/vtool/python\vtool\process_manager\process.py", line 1843, in create_code
#     data_instance.create()
#   File "E:/dev/git/vtool/python\vtool\data.py", line 583, in create
#     util_file.write_lines(filename, self.lines)
#   File "E:/dev/git/vtool/python\vtool\util_file.py", line 2320, in write_lines
#     with open(filepath, write_string) as open_file:
# IOError: [Errno 2] No such file or directory: 'G:/.shortcut-targets-by-id/1i52O7K8ctL5y_7YcNk-THs4qBrefqdLJ/Dr_Reel_Team/Projects/ESPN/LBS_Big_Studios/Simp_Dev/TEMPLATED/Character/GroundskeeperWillie1/add_face/.code/Flat_Pupils/import_flat_pupil_rig/import_flat_pupil_skin_weight/import_flat_pupil_skin_weight.py'
V:		Load process: None

**Comment by louisVottero** [comment]
The error message seems to be a google drive bug.   Should be better now. 
Duplicating code had an issue where checkboxes weren't set properly.  This is fixed here 
https://github.com/louisVottero/vtool/pull/583
