### ISSUE TITLE
Ramen Unreal Error

### ISSUE THREAD

**Issue by louisVottero** [louisVottero/vtool#542]
```
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "J:\site/tools/vtool/python\vtool\ramen\ui_lib\ui_ramen.py", line 162, in _run_graph
LogPython: Error:     eval.run_ui(widget.main_view.base)
LogPython: Error:   File "J:\site/tools/vtool/python\vtool\ramen\eval.py", line 34, in run_ui
LogPython: Error:     run(items)
LogPython: Error:   File "J:\site/tools/vtool/python\vtool\ramen\eval.py", line 65, in run
LogPython: Error:     connected_ins = node.get_input_connected_nodes()
LogPython: Error:   File "J:\site/tools/vtool/python\vtool\ramen\ui_lib\ui_nodes.py", line 3151, in get_input_connected_nodes
LogPython: Error:     found.append(line.source.get_parent())
LogPython: Error: AttributeError: 'NoneType' object has no attribute 'get_parent'
```

**Comment by louisVottero** [comment]
error dealt with a bit more gracefully as of 
https://github.com/louisVottero/vtool/commit/22abe7b2005ef91d553f31b76fb29400aa8ad960
