### ISSUE TITLE
Ramen Bug - is_built

### ISSUE THREAD

**Issue by louisVottero** [louisVottero/vtool#567]
```
# Traceback (most recent call last):
#   File "/users/lrpvottero/git/vtool/python/vtool/ramen/ui_lib/ui_nodes.py", line 486, in _node_connected
#     connect_socket(source_socket, target_socket)
#   File "/users/lrpvottero/git/vtool/python/vtool/ramen/ui_lib/ui_nodes.py", line 4308, in connect_socket
#     source_node.run([source_socket.name](http://source_socket.name/))
#   File "/users/lrpvottero/git/vtool/python/vtool/ramen/ui_lib/ui_nodes.py", line 3371, in run
#     self.run_inputs()
#   File "/users/lrpvottero/git/vtool/python/vtool/ramen/ui_lib/ui_nodes.py", line 4037, in run_inputs
#     super(RigItem, self).run_inputs()
#   File "/users/lrpvottero/git/vtool/python/vtool/ramen/ui_lib/ui_nodes.py", line 3318, in run_inputs
#     self.run_connection(socket_name)
#   File "/users/lrpvottero/git/vtool/python/vtool/ramen/ui_lib/ui_nodes.py", line 3350, in run_connection
#     input_node.run(send_output=send_output)
#   File "/users/lrpvottero/git/vtool/python/vtool/ramen/ui_lib/ui_nodes.py", line 3373, in run
#     self._implement_run(socket)
#   File "/users/lrpvottero/git/vtool/python/vtool/ramen/ui_lib/ui_nodes.py", line 3913, in _implement_run
#     self._run(socket)
#   File "/users/lrpvottero/git/vtool/python/vtool/ramen/ui_lib/ui_nodes.py", line 3865, in _run
#     self.rig.create()
#   File "/users/lrpvottero/git/vtool/python/vtool/ramen/rigs.py", line 435, in create
#     if self.rig_util and self.rig_util.is_built():
#   File "/users/lrpvottero/git/vtool/python/vtool/ramen/rigs.py", line 538, in __getattribute__
#     return object.__getattribute__(self, item)
# AttributeError: 'MayaFkRig' object has no attribute 'is_built'
```

**Comment by louisVottero** [comment]
Fixed Here:
https://github.com/louisVottero/vtool/commit/e2b5abfde6d2cdb1d7174dcad7151bdcb311f867
