### ISSUE TITLE
Maya 2025:  Copy Match doesn't open

### ISSUE THREAD

**Issue by louisVottero** [louisVottero/vtool#576]
```
# Traceback (most recent call last):
#   File "E:\dev/git/vtool/python\vtool\process_manager\ui_view.py", line 64, in _copy_match
#     copy_widget = CopyWidget(show_others=show_others)
#                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "E:\dev/git/vtool/python\vtool\process_manager\ui_view.py", line 1760, in __init__
#     super(CopyWidget, self).__init__(parent)
#   File "E:\dev/git/vtool/python\vtool\qt_ui.py", line 242, in __init__
#     self._build_widgets()
#   File "E:\dev/git/vtool/python\vtool\process_manager\ui_view.py", line 1816, in _build_widgets
#     self.view.setSelectionMode(self.view.ContiguousSelection)
#                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# AttributeError: 'ProcessTreeWidget' object has no attribute 'ContiguousSelection'
```

**Comment by louisVottero** [comment]
https://github.com/louisVottero/vtool/pull/577
