### ISSUE TITLE
Process duplicate error 

### ISSUE THREAD

**Issue by louisVottero** [louisVottero/vtool#581]
```
# Traceback (most recent call last):
#   File "E:\dev/git/vtool/python\vtool\process_manager\ui_view.py", line 920, in _duplicate_process
#     new_process = process.copy_process(source_process, target_directory)
#   File "E:\dev/git/vtool/python\vtool\process_manager\process.py", line 3597, in copy_process
#     copy_process_ramen(source_process, new_process, ramen)
#   File "E:\dev/git/vtool/python\vtool\process_manager\process.py", line 3871, in copy_process_ramen
#     copied_path = util_file.copy_file(filepath, target_filepath)
#   File "E:\dev/git/vtool/python\vtool\util_file.py", line 2657, in copy_file
#     shutil.copyfile(filepath, filepath_destination)
#   File "C:\Program Files\Autodesk\Maya2023\Maya2023\Python\lib\shutil.py", line 265, in copyfile
#     with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
# FileNotFoundError: [Errno 2] No such file or directory: 'E:/dev/vetala/test/process9/.ramen/graphs/graph1/ramen.json'
```

**Comment by louisVottero** [comment]
Fixed Here 
https://github.com/louisVottero/vtool/pull/583
