### ISSUE TITLE
Create Data Error

### ISSUE THREAD

**Issue by louisVottero** [louisVottero/vtool#587]
```
# Traceback (most recent call last):
#   File "E:\dev/git/vtool/python\vtool\process_manager\ui_data.py", line 229, in _data_item_selection_changed
#     process_tool.cache_data_type_read(item_name)
#   File "E:\dev/git/vtool/python\vtool\process_manager\process.py", line 1543, in cache_data_type_read
#     util_file.ReadCache.cache_read_data(data_type)
#   File "E:\dev/git/vtool/python\vtool\util_file.py", line 1217, in cache_read_data
#     file_data = get_json(path)
#   File "E:\dev/git/vtool/python\vtool\util_file.py", line 1868, in get_json
#     if os.stat(filepath).st_size == 0:
# FileNotFoundError: [WinError 2] The system cannot find the file specified: 'E:/dev/vetala/test/process3/.data/test/data.json'

```

**Comment by louisVottero** [comment]
should be fixed here
https://github.com/louisVottero/vtool/issues/587
