### ISSUE TITLE
Error: Ramen Maya, nothing in the Shape variable on FkRig node 

### ISSUE THREAD

**Issue by louisVottero** [louisVottero/vtool#588]
```
# Traceback (most recent call last):
#   File "/users/lrpvottero/git/vtool/python/vtool/ramen/ui_lib/ui_nodes.py", line 487, in _node_connected
#     connect_socket(source_socket, target_socket)
#   File "/users/lrpvottero/git/vtool/python/vtool/ramen/ui_lib/ui_nodes.py", line 4339, in connect_socket
#     target_node.set_socket([target_socket.name](http://target_socket.name/), value, run=run_target)
#   File "/users/lrpvottero/git/vtool/python/vtool/ramen/ui_lib/ui_nodes.py", line 3226, in set_socket
#     self.run()
#   File "/users/lrpvottero/git/vtool/python/vtool/ramen/ui_lib/ui_nodes.py", line 3396, in run
#     self._implement_run(socket)
#   File "/users/lrpvottero/git/vtool/python/vtool/ramen/ui_lib/ui_nodes.py", line 3940, in _implement_run
#     self._run(socket)
#   File "/users/lrpvottero/git/vtool/python/vtool/ramen/ui_lib/ui_nodes.py", line 3892, in _run
#     self.rig.create()
#   File "/users/lrpvottero/git/vtool/python/vtool/ramen/rigs.py", line 447, in create
#     self._create()
#   File "/users/lrpvottero/git/vtool/python/vtool/ramen/rigs.py", line 405, in _create
#     self._create_rig()
#   File "/users/lrpvottero/git/vtool/python/vtool/ramen/rigs.py", line 398, in _create_rig
#     self.rig_util.build()
#   File "/users/lrpvottero/git/vtool/python/vtool/ramen/rigs.py", line 527, in __getattribute__
#     result_values = result()
#   File "/users/lrpvottero/git/vtool/python/vtool/ramen/rigs_maya.py", line 735, in build
#     self._create_maya_controls()
#   File "/users/lrpvottero/git/vtool/python/vtool/ramen/rigs_maya.py", line 680, in _create_maya_controls
#     control_inst = self.create_control(description=description)
#   File "/users/lrpvottero/git/vtool/python/vtool/ramen/rigs_maya.py", line 574, in create_control
#     control = self._create_control(description, sub)
#   File "/users/lrpvottero/git/vtool/python/vtool/ramen/rigs_maya.py", line 300, in _create_control
#     control.shape = self.rig.shape
#   File "/users/lrpvottero/git/vtool/python/vtool/ramen/rigs.py", line 301, in __getattribute__
#     return object.__getattribute__(self, item)
#   File "/users/lrpvottero/git/vtool/python/vtool/ramen/rigs.py", line 341, in getter
#     if hasattr(self.rig_util, input_entry_name):
#   File "/users/lrpvottero/git/vtool/python/vtool/ramen/rigs.py", line 538, in __getattribute__
#     return object.__getattribute__(self, item)
#   File "/users/lrpvottero/git/vtool/python/vtool/ramen/rigs_maya.py", line 389, in shape
#     return self.rig.attr.get('shape')[0]
```

**Comment by louisVottero** [comment]
Was unable to create the bug. Hoping this change will solve it
https://github.com/louisVottero/vtool/commit/53eaa3e8edb36639946423c945e04cda3d69d933
